export default {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    CHECK_AUTH_REQUEST: "CHECK_AUTH_REQUEST",
    CHECK_AUTH_SUCCESS: "CHECK_AUTH_SUCCESS",
    CHECK_AUTH_FAILURE: "CHECK_AUTH_FAILURE",

    CLEAR_AUTH_STATE: "CLEAR_AUTH_STATE"
}