export default {
    PROJECT_CREATE_REQUEST: "PROJECT_CREATE_REQUEST",
    PROJECT_CREATE_SUCCESS: "PROJECT_CREATE_SUCCESS",
    PROJECT_CREATE_FAILURE: "PROJECT_CREATE_FAILURE",

    PROJECT_GET_ALL_REQUEST: "PROJECT_GET_ALL_REQUEST",
    PROJECT_GET_ALL_SUCCESS: "PROJECT_GET_ALL_SUCCESS",
    PROJECT_GET_ALL_FAILURE: "PROJECT_GET_ALL_FAILURE",

    CLEAR_PROJECT_STATE: "CLEAR_PROJECT_STATE"
}